# Generated by Django 4.1.4 on 2022-12-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(),
        ),
    ]
